"""add richer match feedback columns to analyses

Revision ID: 1dc6781aba3d
Revises: 2341ca3929e9
Create Date: 2026-07-31 01:31:19.413558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dc6781aba3d'
down_revision: Union[str, None] = '2341ca3929e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('keyword_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analyses', sa.Column('keyword_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analyses', sa.Column('section_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analyses', sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analyses', sa.Column('suggested_bullets', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'suggested_bullets')
    op.drop_column('analyses', 'weaknesses')
    op.drop_column('analyses', 'section_suggestions')
    op.drop_column('analyses', 'keyword_gaps')
    op.drop_column('analyses', 'keyword_matches')
    # ### end Alembic commands ###
