"""multi-tenancy + saved resume labels + tracker fields + BYO key

Revision ID: 5e727e7d5fb9
Revises: 1dc6781aba3d
Create Date: 2026-07-31 01:46:17.008509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e727e7d5fb9'
down_revision: Union[str, None] = '1dc6781aba3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('resume_summary', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('job_summary', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('applied', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    decision_status = sa.Enum('under_review', 'selected', 'not_selected', name='decision_status')
    decision_status.create(op.get_bind(), checkfirst=True)
    op.add_column('analyses', sa.Column('decision', decision_status, nullable=True))
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    op.create_foreign_key(None, 'analyses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('resumes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('label', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('encrypted_api_key', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('api_provider', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_provider')
    op.drop_column('users', 'encrypted_api_key')
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_column('resumes', 'label')
    op.drop_column('resumes', 'user_id')
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.drop_column('analyses', 'decision')
    op.execute('DROP TYPE decision_status')
    op.drop_column('analyses', 'applied')
    op.drop_column('analyses', 'job_summary')
    op.drop_column('analyses', 'resume_summary')
    op.drop_column('analyses', 'user_id')
    # ### end Alembic commands ###
