"""auth: email_verified, auth_provider, nullable password

Revision ID: c7143bb2d206
Revises: 5e727e7d5fb9
Create Date: 2026-07-31 07:26:33.224258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7143bb2d206'
down_revision: Union[str, None] = '5e727e7d5fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
